<a href="https://colab.research.google.com/github/zanasaed/NoteBook/blob/main/colab_cheet_sheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Colab

<img height="45px" src="https://colab.research.google.com/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px">

<h1>Welcome to Colaboratory!</h1>

Colaboratory is a free Jupyter notebook environment that requires no setup and runs entirely in the cloud.

With Colaboratory you can write and execute code, save and share your analyses, and access powerful computing resources, all for free from your browser.

In [ ]:
#@title Introducing Colaboratory
#@markdown This 3-minute video gives an overview of the key features of Colaboratory:
from IPython.display import YouTubeVideo
YouTubeVideo('inN8seMm7UI', width=600, height=400)

## Getting Started

The document you are reading is a  [Jupyter notebook](https://jupyter.org/), hosted in Colaboratory. It is not a static page, but an interactive environment that lets you write and execute code in Python and other languages.

For example, here is a **code cell** with a short Python script that computes a value, stores it in a variable, and prints the result:

In [ ]:
seconds_in_a_day = 24 * 60 * 60
seconds_in_a_day

86400

To execute the code in the above cell, select it with a click and then either press the ▷ button to the left of the code, or use the keyboard shortcut "⌘/Ctrl+Enter".

All cells modify the same global state, so variables that you define by executing a cell can be used in other cells:

In [ ]:
seconds_in_a_week = 7 * seconds_in_a_day
seconds_in_a_week

604800

For more information about working with Colaboratory notebooks, see [Overview of Colaboratory](/notebooks/basic_features_overview.ipynb).


## More Resources

Learn how to make the most of Python, Jupyter, Colaboratory, and related tools with these resources:

### Working with Notebooks in Colaboratory
- [Overview of Colaboratory](/notebooks/basic_features_overview.ipynb)
- [Guide to Markdown](/notebooks/markdown_guide.ipynb)
- [Importing libraries and installing dependencies](/notebooks/snippets/importing_libraries.ipynb)
- [Saving and loading notebooks in GitHub](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb)
- [Interactive forms](/notebooks/forms.ipynb)
- [Interactive widgets](/notebooks/widgets.ipynb)

### Working with Data
- [Loading data: Drive, Sheets, and Google Cloud Storage](/notebooks/io.ipynb) 
- [Charts: visualizing data](/notebooks/charts.ipynb)
- [Getting started with BigQuery](/notebooks/bigquery.ipynb)

### Machine Learning Crash Course
These are a few of the notebooks from Google's online Machine Learning course. See the [full course website](https://developers.google.com/machine-learning/crash-course/) for more.
- [Intro to Pandas](/notebooks/mlcc/intro_to_pandas.ipynb)
- [Tensorflow concepts](/notebooks/mlcc/tensorflow_programming_concepts.ipynb)
- [First steps with TensorFlow](/notebooks/mlcc/first_steps_with_tensor_flow.ipynb)
- [Intro to neural nets](/notebooks/mlcc/intro_to_neural_nets.ipynb)
- [Intro to sparse data and embeddings](/notebooks/mlcc/intro_to_sparse_data_and_embeddings.ipynb)

### Using Accelerated Hardware
- [TensorFlow with GPUs](/notebooks/gpu.ipynb)
- [TensorFlow with TPUs](/notebooks/tpu.ipynb)

## Machine Learning Examples: Seedbank

To see end-to-end examples of the interactive machine learning analyses that Colaboratory makes possible, check out the [Seedbank](https://research.google.com/seedbank/) project.

A few featured examples:

- [Neural Style Transfer](https://research.google.com/seedbank/seed/neural_style_transfer_with_tfkeras): Use deep learning to transfer style between images.
- [EZ NSynth](https://research.google.com/seedbank/seed/ez_nsynth): Synthesize audio with WaveNet auto-encoders.
- [Fashion MNIST with Keras and TPUs](https://research.google.com/seedbank/seed/fashion_mnist_with_keras_and_tpus): Classify fashion-related images with deep learning.
- [DeepDream](https://research.google.com/seedbank/seed/deepdream): Produce DeepDream images from your own photos.
- [Convolutional VAE](https://research.google.com/seedbank/seed/convolutional_vae): Create a generative model of handwritten digits.

# set up VSCode on Google Colab
for see more detail go to this [link](https://github.com/amitness/amitness.github.io/blob/63cdc0abc5e7394860da3c53f9d72a4cd3545874/_posts/2020-09-01-vscode-on-colab.md)

In [ ]:
!pip install colabcode
from colabcode import ColabCode
ColabCode()


# Natural Language Processing in TensorFlow


## **Week1**

### Using APIs



The fit on texts method of the tokenizer then takes in the data and encodes it.

The tokenizer provides a word index property which returns a dictionary containing key value pairs, where the key is the word, and the value is the token for that word, which you can inspect by simply printing it out.


In [ ]:
import tensorflow as tf 
from tensorflow import keras 
from tensorflow.keras.preprocessing.text import Tokenizer

sentences = [
             'I love my dog ',
             'I love my cat',
             'You love my dog!'

]

tokenizer = Tokenizer(num_words = 100 )
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
print(word_index)

{'love': 1, 'my': 2, 'i': 3, 'dog': 4, 'cat': 5, 'you': 6}


### Text to sequence




If you train a neural network on a corpus of texts, and the text has a word index generated from it, then when you want to do inference with the train model, you'll have to encode the text that you want to infer on with the same word index, otherwise it would be meaningless.


One really handy thing about this that you'll use later is the fact that the text to sequences called can take any set of sentences, so it can encode them based on the word set that it learned from the one that was passed into fit on texts.

So I really love my dog would still be encoded as 4, 2, 1, 3, which is 'I love my dog' with 'really' being lost as the word is not in the Word Index, and 'my dog loves my manatee' would get encoded to 1, 3, 1, which is just 'my dog my'.

In [ ]:
import tensorflow as tf 
from tensorflow import keras 
from tensorflow.keras.preprocessing.text import Tokenizer

sentences = [
             'I love my dog ',
             'I love my cat',
             'You love my dog!',
             'Do you think my dog is amazing?'

]

tokenizer = Tokenizer(num_words = 100 )
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
sequence = tokenizer.texts_to_sequences(sentences)

print(word_index)
print(seqquence)

{'my': 1, 'love': 2, 'dog': 3, 'i': 4, 'you': 5, 'cat': 6, 'do': 7, 'think': 8, 'is': 9, 'amazing': 10}
[[4, 2, 1, 3], [4, 2, 1, 6], [5, 2, 1, 3], [7, 5, 8, 1, 3, 9, 10]]


### Looking more at the Tokenizer


So what do we learn from this? First of all, we really need a lot of training data to get a broad vocabulary or we could end up with sentences like, my dog my, like we just did.

Secondly, in many cases, it's a good idea to instead of just ignoring unseen words, to put a special value in when an unseen word is encountered.


In [ ]:
import tensorflow as tf 
from tensorflow import keras 
from tensorflow.keras.preprocessing.text import Tokenizer

sentences = [
             'I love my dog ',
             'I love my cat',
             'You love my dog!',
             'Do you think my dog is amazing?'

]

tokenizer = Tokenizer(num_words = 100 , oov_token='<OOV>')
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
sequence = tokenizer.texts_to_sequences(sentences)

print(word_index)
print(seqquence)

{'<OOV>': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11}
[[4, 2, 1, 3], [4, 2, 1, 6], [5, 2, 1, 3], [7, 5, 8, 1, 3, 9, 10]]


### Padding







So I've made a few changes to the code to handle padding.

First, in order to use the padding functions you'll have to import pad sequences from tensorflow.carastoppreprocessing.sequence.


Then once the tokenizer has created the sequences, these sequences can be passed to pad sequences in order to have them padded like this.


You can now see that the list of sentences has been padded out into a matrix and that each row in the matrix has the same length.


Often you'll see examples where the padding is after the sentence and not before as you just saw.


If you, like me, are more comfortable with that, you can change the code to this, adding the parameter padding equals post.


You may have noticed that the matrix width was the same as the longest sentence.


If I have sentences longer than the maxlength, then I'll lose information but from where.Like with the padding the default is pre, which means that you will lose from the beginning of the sentence.
If you want to override this so that you lose from the end instead, you can do so with the truncating parameter like this.



In [ ]:
import tensorflow as tf 
from tensorflow import keras 
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
sentences = [
             'I love my dog ',
             'I love my cat',
             'You love my dog!',
             'Do you think my dog is amazing?'

]

tokenizer = Tokenizer(num_words = 100 , oov_token='<OOV>')
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index

sequence = tokenizer.texts_to_sequences(sentences)

padded = pad_sequences(sequence , padding='post' , maxlen=5 , truncating='post' )

print("***\n",word_index)
print("***\n",seqquence)
print("***\n",padded)

***
 {'<OOV>': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11}
***
 [[4, 2, 1, 3], [4, 2, 1, 6], [5, 2, 1, 3], [7, 5, 8, 1, 3, 9, 10]]
***
 [[5 3 2 4 0]
 [5 3 2 7 0]
 [6 3 2 4 0]
 [8 6 9 2 4]]


### Sarcasm, really?

[link](https://www.coursera.org/learn/natural-language-processing-tensorflow/lecture/HAUby/sarcasm-really)

### Working with the Tokenizer
[link ](https://www.coursera.org/learn/natural-language-processing-tensorflow/lecture/VEUJX/working-with-the-tokenizer)

### Notebook for lesson 3
[link](https://www.coursera.org/learn/natural-language-processing-tensorflow/lecture/uskDE/notebook-for-lesson-3)


## Week2

### Introduction
[link ](https://coursera.org/learn/natural-language-processing-tensorflow/lecture/1OiEp/introduction)

### The IMBD dataset
[link](https://www.coursera.org/learn/natural-language-processing-tensorflow/lecture/PxiP4/the-imbd-dataset)

### Looking into the details
[link](https://www.coursera.org/learn/natural-language-processing-tensorflow/lecture/0N8WC/looking-into-the-details)

### How can we use vectors?
[link ](https://www.coursera.org/learn/natural-language-processing-tensorflow/lecture/HKvYY/how-can-we-use-vectors)


In [ ]:
import tensorflow_datasets as tfds

imdb, info = tfds.load("imdb_reviews", with_info= True, as_supervised=True)

In [ ]:
import numpy as np
 
train_data, test_data = imdb['train'], imdb['test']

training_sentences = []
training_labels = []

testing_sentences = [] 
testing_labels = [] 

for s,l in train_data :
    training_sentences.append(str(s.numpy()))
    training_labels.append(l.numpy())

for s, l in test_data:
    testing_sentences.append(str(s.numpy()))
    testing_labels.append(l.numpy())



# Udemy - Complete Guide to TensorFlow for Deep Learning with Python 2018-11


[linkt to descrption of course ](https://colab.research.google.com/drive/1Qf9oRvqqlJRxMyzaQCSjKdEghf8dOAJ6)